import jsPDF from "jspdf";
import type { RepoData } from "@/types/repo";

export function downloadPDF(repo: RepoData, score: number) {

  const doc = new jsPDF();

  let y = 20;

  doc.setFontSize(22);
  doc.text("DeployAI Report", 20, y);

  y += 15;

  doc.setFontSize(12);

  doc.text(`Repository: ${repo.name}`, 20, y);
  y += 10;

  doc.text(`Owner: ${repo.owner}`, 20, y);
  y += 10;

  doc.text(`Framework: ${repo.framework}`, 20, y);
  y += 10;

  doc.text(`Language: ${repo.language}`, 20, y);
  y += 10;

  doc.text(`Stars: ${repo.stars}`, 20, y);
  y += 10;

  doc.text(`Forks: ${repo.forks}`, 20, y);
  y += 10;

  doc.text(`Health Score: ${score}/100`, 20, y);
  y += 15;

  doc.setFontSize(16);
  doc.text("Repository Inspection",20,y);

  y+=10;

  doc.setFontSize(12);

  doc.text(`README: ${repo.hasReadme?"Found":"Missing"}`,20,y);
  y+=8;

  doc.text(`Dockerfile: ${repo.hasDockerfile?"Found":"Missing"}`,20,y);
  y+=8;

  doc.text(`GitHub Actions: ${repo.hasGithubActions ? "Found" : "Missing"}`, 20, y);
  y += 8;

  doc.text(`LICENSE: ${repo.hasLicense ? "Found" : "Missing"}`, 20, y);
  y+=15;

  doc.setFontSize(16);
  doc.text("Deployment Recommendation",20,y);

  y+=10;

  let platform="Docker";

  switch(repo.framework){

      case "Next.js":
          platform="Vercel";
          break;

      case "React":
          platform="Netlify";
          break;

      case "Express":
          platform="Railway";
          break;

      case "FastAPI":
          platform="Railway";
          break;

      case "Spring Boot":
          platform="AWS EC2";
          break;

      case "Electron":
          platform="Desktop Distribution";
          break;

  }

  doc.setFontSize(12);

  doc.text(`Recommended Platform: ${platform}`,20,y);

  y+=10;

  doc.text("Generated by DeployAI",20,280);

  doc.save(`${repo.name}-DeployAI-Report.pdf`);

}